# Filterbank config
filterbank:
  n_filters: 512
  kernel_size: 16
  stride: 8
# Network config
speakerstack:
  n_blocks_spk: 14
  n_repeats_spk: 1
  mask_act_spk: relu
  bn_chan_spk: 128
  skip_chan_spk: 128
  hid_chan_spk: 512
# Network config
separationstack:
  n_blocks_sep: 11
  n_repeats_sep: 4
  mask_act_sep: relu
  bn_chan_sep: 128
  skip_chan_sep: 128
  hid_chan_sep: 512
# Training config
training:
  epochs: 200
  batch_size: 8
  num_workers: 4
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  train_dir: data/wav8k/min/tr/
  valid_dir: data/wav8k/min/cv/
  task: sep_clean
  nondefault_nsrc:
  sample_rate: 8000
  mode: min
